import type { NextPage } from 'next'
import Head from 'next/head'
import FeaturedPost from '../components/FeaturedPost'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FeaturedPost postSummary={{
        id: 42,
        slug: "como-fazer-x-coisas-com-react-js",
        title: "Como fazer X coisas com React.js",
        imageUrls: {
          default: "/laptop.jpg",
          small: "/laptop.jpg",
          medium: "/laptop.jpg",
          large: "/laptop.jpg",
        },
        editor: {
          id: 29,
          name: "Daniel Bonifacio",
          avatarUrls: {
            default:
              "https://storage.googleapis.com/alganews-files/posts/avatar-joao.jpeg",
            small:
              "https://storage.googleapis.com/alganews-files/posts/avatar-joao-small.jpeg",
            medium:
              "https://storage.googleapis.com/alganews-files/posts/avatar-joao-medium.jpeg",
            large:
              "https://storage.googleapis.com/alganews-files/posts/avatar-joao-large.jpeg",
          },
          createdAt: "2017-03-04T00:12:45Z",
        },
        createdAt: "2020-12-04T00:12:45-03:00",
        updatedAt: "2020-12-05T00:12:45-03:00",
        published: true,
        tags: ["JavaScript", "react"],
        canBePublished: true,
        canBeUnpublished: true,
        canBeDeleted: true,
        canBeEdited: true,
      }} />
    </div>
  )
}

export default Home
